### ISSUE TITLE
Code hurdles

### ISSUE THREAD

**Issue by bpodrygajlo** [spicylobstergames/shotcaller-godot#138]
In orders.gd we have

`const player_leaders_orders = {}`

This is used first in a function called build_leaders() - still in orders.gd

```
func build_leaders():
	for leader in game.player_leaders:
		player_leaders_orders[leader.name] = new_orders()
```

and

```
func new_orders():
	return {
		"priority": ["pawn", "leader", "building"],
		"tactics": {
			"tactic": "default",
			"speed": 0
		}
	}
```
	
This is a dictionary of orders for every leader.

1. In a c++ game engine this would be part of the leader constructor. `new_orders()` is just a default value.
   Every unit in the game has this dictionary. Only the Main/Unit scene actualy uses it. In godot this could be a part of a _ready() function or just an `onready` default value inside unit/leader class.
2. build_leaders is a misleading function name. The same name is used four times in different nodes. If something is called "build" it should create an entity from start to finish. And reusing the name is very confusing.
3. This was brought up before but everything in this game is a string, and we need to compare them constantly. String compare is not optimal. Plus coding is more difficult because the editor doesn't hint anything. You just have to remember every magic string in the game.

Then we have leaders_cycle. This is a function that is called every 4 seconds from a self-calling function.
```
func leaders_cycle(): # called every 4 sec
	for leader in game.player_leaders:
		set_leader(leader, player_leaders_orders[leader.name])
		
	for leader in game.enemy_leaders:
		set_leader(leader, enemy_leaders_orders[leader.name])
```

1. Recursion is evil, regardless if its actual function call or just a yield to itself
2. what is "set_leader"? Name tells me nothing about what is inside. It definetly will not be setting any leaders.

Now there is a set of functions:

`orders.set_leader_tactic`, `orders.set_leader_priority` - they handle player input/ AI decision

`orders.set_leader` - updates the orders to the unit - why is this delay necessary?
Can the player not just order the unit and have it do what he wants to do?

More on build_leaders() : The other part not mentioned above:

```
	var timer := Timer.new()
	timer.wait_time = 1
	game.map.add_child(timer)
	timer.start()
# warning-ignore:return_value_discarded
	timer.connect("timeout", self, "hp_regen_cycle")
```

This starts a global timer that starts hp_regen_cycle. This in turn causes regeneration to happen. Regeneration also updates items.

1. This is spaghetti, no defending it.

**Comment by rafaelcastrocouto** [comment]
Ok, that's a lot in one take so I'll try to split in possible solutions/improvements.
Notice that most of your critiques are all basically related to orders.gd, this was one of the latest 'gameplay' contributions I've made and it had the single purpose of making the former release playable. It is far from the desired final product and most of it is already being refactored by @jrdoughty into the GOAP ai system

Putting all that aside, let's get into how we can improve our current code:

The function 'build_leaders' that live inside orders.gd clearly buils the leaders orders (imho that seemd pretty clear at the time). You can rename it to a better name if you have an idea ... maybe 'build_leaders_orders'?! Although it would look kinda redundant to call 'orders.build_leaders_orders(...)'

I usually use 'build' to avoid using 'create' or 'populate' since those are most commonlly already part of the API. Again, if you have a better sugestion I really wanna hear it!

As for having a Leader class, that would require any kind of upgrade system from pawns to leaders to somehow manage the classes, and I'm trying to avoid that if possible. 

I have no issues with us moving the orders into the units (it would make it easier to upgrade them to leaders), we should keep track of possible memory implications.

The delay in orders.set_leader is an intentional part of the shotcaller game idea from @erlend-sh . We are gonna make it so all controls are delayed to move away from the 'fast fingers' gameplay style (typical from players) and closer to the strategic decision mad from coaches 'calling the shots'.

Leaders cycle can be easily fixed to actually use the Timer node ... seems I somehow forgot that the timer node already repeats itself when 'one_shot' in false.

Plz keep comming with the critics, they will push our code forward!

**Comment by bpodrygajlo** [comment]
> Ok, that's a lot in one take so I'll try to split in possible solutions/improvements. Notice that most of your critiques are all basically related to `orders.gd`, this was one of the latest "gameplay" contributions I've made and it had the single purpose of making the former release playable. It is far from the desired final product and most of it is already being refactored by @jrdoughty into the GOAP ai system. This file should be further split into wood system, conquer system, mine/tax system, etc.

I'm not trying to put the blame on anyone. Just what frustrates me about the code I am working in.

> Putting all that aside, let's get into how we can improve our current code:
> 
> The function `build_leaders` that live inside `orders.gd` clearly builds the leaders orders (imho that seemed pretty clear to me at the time). You can rename it to a better name if you have an idea ... maybe `build_leaders_orders`?! Although it would look kinda redundant to call `orders.build_leaders_orders(...)` (same argument applies to `set_ leader`)
> 
> I usually use `build` to avoid using `create` or `populate` since those are most commonlly already part of the API. Again, if you have a better sugestion I really wanna hear it!
> 
> As for having a `Leader` class, that would require any kind of upgrade system (from pawns to leaders) to somehow manage the classes, and I'm trying to avoid that if possible.
>
> I have no issues with us moving the orders into the units (it would make it easier to upgrade them to leaders), we should keep track of possible memory implications.

How about a `_ready()` function for the Unit class that can do that? e.g.:
```
func _ready():
  if type == "leader":
    //what `build_leaders` does
```

> The delay in `orders.set_leader` is a intentional part of the shotcaller game idea from @erlend-sh . We are gonna make it so all controls are delayed to move away from the 'fast fingers' gameplay style (typical from players) and closer to the strategic decision made by coaches 'calling the shots'.

This will not feel right to the player. Depending on when the order is made the execution comes 0-4 seconds later. It should either be always `x` seconds or we need to add some UI element so the player knows when the execution happens.

> Leaders cycle can be easily fixed to actually use the `Timer` node ... ~seems I somehow forgot that the timer node already repeats itself when `one_shot` is set to `false`~. [edit] actually i just found the error, it was one function call that should not be indented so i fixed it by removing two spaces ... [lol](https://github.com/spicylobstergames/shotcaller-godot/commit/ec9428fefe9a30cea02bf43514802d157a52103a) [/edit] (i saw no recursion there)

Having this be part of the `game` node would make most sense to me. But see my previous comment why I don't like the idea to make the delay vary depending on the order issue time.

> Having all "1s hp changing" (damage over time and regen) into one call might seem "spaghetti" but spreading it all over also don't sounds optimal. Note that 'dot' right now only applies via items, but in the future nothing prevents that it comes from skills, buffs, special attacks, etc.

For the spaghetti comment, I think your link illustrates this well:

This is the callstack:
`game` calls `maps.setup_leaders()` - this calls several UI functions. Why is this part of `map`?
`setup_leaders()` calls `game.ui.orders_menu.build_leaders()` 
`game.ui.orders_menu.build_leaders()` calls `game.unit.orders.build_leaders()` - Why is a UI element calling a leader constructor?
`game.unit.orders.build_leaders()` starts the regen cycle - Why are orders responsible for setting up the regen cycle?

A proper way to do this would be:
`game` -> `ui.display_leaders` -> `orders_menu.display_leaders` - // Example name
`game` -> start regen cycle
`game` -> start item update cycle

And either:
`Unit` -> `_ready()` for the default orders
or 
`game` -> `orders.build_leaders()` if we don't move the constructor into `Unit`

Why is this important? We want the names of each node/class to represent what it does. We want our `class Cat` to `meow()` and our `class Dog` to `bark()`. Currently with `map` displaying UI elements and constructing leaders it's a cat that meows, barks and moos.

We also want `map` to not be aware of `ui`. Having it call `game.ui` makes the whole thing difficult to modify and debug. None of the UI elements seems to work as separate instances. And modifying the implementation would require changing `game`, `map` `orders_menu` and maybe `orders`.

> Plz keep comming with the critics, they will push our code forward!

I need to say I am sorry for the initial tone of the post. I wasn't trying to attack you!

**Comment by rafaelcastrocouto** [comment]
No offence taken, I'm glad we can cooperate and dimish any frustration.

> How about a _ready() function for the Unit class that can do that? e.g.:

Right now we can use this solution, but if we create a leader preview, or use the units in any situation out of the map, we would run the function when it's not necessary.

> This will not feel right to the player. Depending on when the order is made the execution comes 0-4 seconds later. It should either be always x seconds or we need to add some UI element so the player knows when the execution happens.

I'm not sure I agree with the player feeling, but the UI element will most likely live along the game clock on the top of the screen (like dota2 day/night indicator)

> maps.setup_leaders() - this calls several UI functions. Why is this part of map?

Because we have maps with different number and types of leaders, so we first need to load the map to know how we are going to spawn the leaders.

> game.unit.orders.build_leaders() - Why is a UI element calling a leader constructor?

Constructor? Where? I'm not sure what you are talking about. This function populates the leaders orders list.

> Why are orders responsible for setting up the regen cycle?   

The regen cycle could be started somewhere else on the code, the place it resides right now is clearly due to the authoring of the code. Nothing prevents moving it to a place where it makes more sense. The idea of moving it all to game.gd ain't bad, but we gotta take care since that's the stating point and imho it should be a welcoming place that indicates how the code works instead of a huge index.

> Currently with map displaying UI elements and constructing leaders it's a cat that meows, barks and moos.

You will quickly learn that there's a limit on how much you can make you code agnostic, and that the more you use a 'class' the more it will need to be bended to fit your needs. You can push this to the limit and make each piece of your code an independent lib, but you will either have unnecessary layers of abstraction, or you will have very specific libs that only work for your code. 

Yes, the map will change some parts of the UI. Yes the leaders orders will change the gold received. Yes the unit behavior will change the UI. They are all connected and there's no escaping this complexity. All we can do is arrange it the best way in order to make it easier to further develop and understand.

By that I'm not saying that the code is already arranged in the best way possible, far from it ... it is a prototype and it should be better arranged. But to think that one will be able to separate each 'part' of a game by that erase the complexity of their relation is very ingenuous.

I think the best article to guide us in this discussion is this [scene_organization godot doc](https://docs.godotengine.org/en/stable/tutorials/best_practices/scene_organization.html) 
Unfortunately I've read it after the refactorization and most of my code don't follow those guidelines. 
So we could start trying to make it happen, what do you think?

**Comment by jrdoughty** [comment]
If we can come up with a list of stuff like this where we know what we want it to look like, I'll take a crack at it. I'm the weird guy who enjoys refactors because its a programming challenge I can do at night. I have probably another week before GOAP is integrated with the lumberjack due to my shaky availability, but I could help with some of this after that.

**Comment by bpodrygajlo** [comment]
> No offence taken, I'm glad we can cooperate and dimish any frustration.
> 
> > How about a _ready() function for the Unit class that can do that? e.g.:
> 
> Right now we can use this solution, but if we create a leader preview, or use the units in any situation out of the map, we would run the function when it's not necessary.
> 
> > This will not feel right to the player. Depending on when the order is made the execution comes 0-4 seconds later. It should either be always x seconds or we need to add some UI element so the player knows when the execution happens.
> 
> I'm not sure I agree with the player feeling, but the UI element will most likely live along the game clock on the top of the screen (like dota2 day/night indicator)
> 
> > maps.setup_leaders() - this calls several UI functions. Why is this part of map?
> 
> Because we have maps with different number and types of leaders, so we first need to load the map to know how we are going to spawn the leaders.
> 
> > game.unit.orders.build_leaders() - Why is a UI element calling a leader constructor?
> 
> Constructor? Where? I'm not sure what you are talking about. This function populates the leaders orders list. ([in godot _init is the default Class constructor](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#class-constructor)

It's creates data related to a single instance of a Node subclass. Whether its called `_init` or something else it is in essence part of the constructor for the `Unit` class and should be part of the aforementioned `_init` or `_ready` function.
 
> > Why are orders responsible for setting up the regen cycle?
> 
> The regen cycle could be started somewhere else on the code, the place it resides right now is clearly due to the authoring of the code. Nothing prevents moving it to a place where it makes more sense. The idea of moving it all to game.gd ain't bad, but we gotta take care since that's the stating point and imho it should be a welcoming place that indicates how the code works instead of a huge index.
> 
> > Currently with map displaying UI elements and constructing leaders it's a cat that meows, barks and moos.
> 
> You will quickly learn that there's a limit on how much you can make you code agnostic, and that the more you use a 'class' the more it will need to be bended to fit your needs. You can push this to the limit and make each piece of your code an independent lib, but you will either have unnecessary layers of abstraction, or you will have very specific libs that only work for your code.

I've been working with godot for a year now. When I say it can be done I don't hypothesize, I've done it in my games. I think what you mean is the loose coupling which is mentioned in the godot design doc. This can be done through signals (my preferred way) or references to node, path or function (shotcallers way). I think either one is good and I use both in my games depending on which one is more appropriate.

> Yes, the map will change some parts of the UI. Yes the leaders orders will change the gold received. Yes the unit behavior will change the UI. They are all connected and there's no escaping this complexity. All we can do is arrange it the best way in order to make it easier to further develop and understand.

I want to have it arranged so that map doesn't change the UI, orders don't change gold received, and behavior doesn't change the UI.

> By that I'm not saying that the code is already arranged in the best way possible, far from it ... it is a prototype and it should be better arranged. But to think that one will be able to separate each 'part' of a game and by that erase the complexity of their relation is very ingenuous.
> 
> I think the best article to guide us in this discussion is this [scene_organization godot doc](https://docs.godotengine.org/en/stable/tutorials/best_practices/scene_organization.html) Unfortunately I've read it after the refactorization and most of my code don't follow those guidelines. So we could start trying to make it happen, what do you think?

I agree we should follow this.

**Comment by rafaelcastrocouto** [comment]
> It's creates data related to a single instance of a Node subclass. Whether its called _init or something else it is in essence part of the constructor for the Unit class and should be part of the aforementioned _init or _ready function.

The unit node is getting really bloated, that's why I was trying to decouple orders from units. This way if someone uses the code to create another game that do not have orders, they will be able to do it easily.

> I want to have it arranged so that map doesn't change the UI, orders don't change gold received, and behavior doesn't change the UI.

I'm not sure how you wish to achieve this but I'm really curious.

Right now me and John are trying to solve a possible leak, maybe a better structure will help avoid this kind of issues. I'm pretty sure work together to avoid all the hurdles and get to a good result. 

Can I close this issue and continue this conversation on the community channel? I'm feeling this thread is getting too long, maybe we can create more specific issues to be more productive?

**Comment by erlend-sh** [comment]
> Depending on when the order is made the execution comes 0-4 seconds later. It should either be always x seconds or we need to add some UI element so the player knows when the execution happens.

Yeah, it should be a fixed ~3s delay (sometimes faster/slower because of a reward/punishment). I know we agreed on that in chat a long time ago but we seem to have lost track of it.

**Comment by rafaelcastrocouto** [comment]
100% burried ... sorry for that.
I've opened [another issue](https://github.com/spicylobstergames/shotcaller-godot/issues/151) for the control cooldown and I'm wokring on it.

**Comment by rafaelcastrocouto** [comment]
I've implemented the control cooldown and moved the methods mentioned in the oders file to the unit file (set_dot, set_heal, etc) as suggested by the OP.

I hope we can move on from this issue now ... or did something else got burried?

**Comment by rafaelcastrocouto** [comment]
since it's been over a week with no responses, I'm closing this issue.
